import { GlassCard } from '../ui/GlassCard';
import { Button } from '../ui/Button';
import type { NextStep } from '../../types';

interface NextStepsChecklistProps {
  steps: NextStep[];
  onToggleStep: (id: string) => void;
  onSchedule: () => void;
}

export function NextStepsChecklist({
  steps,
  onToggleStep,
  onSchedule,
}: NextStepsChecklistProps) {
  return (
    <GlassCard className="flex flex-col h-full justify-between gap-md border-outline-variant/60 bg-surface-container/30 hover:border-outline/40 transition-all font-body text-left p-lg">
      <div className="flex flex-col gap-sm">
        <h3 className="font-headline font-bold text-headline-sm text-on-surface select-none">
          Next Steps Checklist
        </h3>
        <p className="text-body-sm text-on-surface-variant leading-relaxed select-none">
          Actionable follow-up items generated by AI to close remaining role alignment gaps.
        </p>

        {/* Checklist */}
        <div className="flex flex-col gap-sm mt-xs">
          {steps.map((step) => (
            <label
              key={step.id}
              onClick={() => onToggleStep(step.id)}
              className="flex gap-sm p-sm rounded-xl bg-surface-container-low border border-outline-variant/50 cursor-pointer select-none items-start hover:border-primary-container/30 hover:bg-surface-container-high/40 transition-all duration-300"
            >
              <input
                type="checkbox"
                checked={step.completed}
                readOnly
                className="mt-1 accent-primary rounded cursor-pointer pointer-events-none"
              />
              <div className="flex flex-col gap-[2px]">
                <span
                  className={`text-body-sm font-bold leading-none ${
                    step.completed ? 'line-through text-outline' : 'text-on-surface'
                  }`}
                >
                  {step.title}
                </span>
                <span
                  className={`text-body-xs leading-normal mt-[2px] ${
                    step.completed ? 'line-through text-outline/70' : 'text-on-surface-variant'
                  }`}
                >
                  {step.description}
                </span>
              </div>
            </label>
          ))}
        </div>
      </div>

      <div className="border-t border-outline-variant/30 pt-md mt-sm select-none">
        <Button variant="primary" icon="calendar_month" onClick={onSchedule} className="w-full">
          Schedule Follow-up
        </Button>
      </div>
    </GlassCard>
  );
}