import type { Config } from 'tailwindcss';

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#0b1326',
        surface: '#0b1326',
        'surface-dim': '#0b1326',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-bright': '#31394d',
        'surface-variant': '#2d3449',
        primary: '#bdc2ff',
        'primary-container': '#818cf8',
        'on-primary': '#131e8c',
        'on-primary-container': '#101b8a',
        'primary-fixed': '#e0e0ff',
        'primary-fixed-dim': '#bdc2ff',
        'on-primary-fixed': '#000767',
        'on-primary-fixed-variant': '#2f3aa3',
        secondary: '#b9c7e0',
        'secondary-container': '#3c4a5e',
        'on-secondary': '#233144',
        'on-secondary-container': '#abb9d2',
        'secondary-fixed': '#d5e3fd',
        'secondary-fixed-dim': '#b9c7e0',
        'on-secondary-fixed': '#0d1c2f',
        'on-secondary-fixed-variant': '#3a485c',
        tertiary: '#f7bd3e',
        'tertiary-container': '#c08d00',
        'on-tertiary': '#402d00',
        'on-tertiary-container': '#3e2b00',
        'tertiary-fixed': '#ffdea3',
        'tertiary-fixed-dim': '#f7bd3e',
        'on-tertiary-fixed': '#261900',
        'on-tertiary-fixed-variant': '#5d4200',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        outline: '#908f9e',
        'outline-variant': '#454653',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#c6c5d5',
        'on-background': '#dae2fd',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        'inverse-primary': '#4953bc',
        'surface-tint': '#bdc2ff',
      },
      fontFamily: {
        headline: ['"Hanken Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Geist', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['1.25rem', { lineHeight: '1.25', fontWeight: '700' }],
        'headline-md': ['1.75rem', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['2.5rem', { lineHeight: '1.15', fontWeight: '800' }],
        'headline-xl': ['3.75rem', { lineHeight: '1.1', fontWeight: '800' }],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
      },
    },
  },
  plugins: [],
} satisfies Config;